name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleRelease

    - name: Sign Android release
      uses: r0adkll/sign-android-release@v1
      with:
        # The directory to find your release to sign
        releaseDirectory: ./app/build/outputs/apk/release
        # The key used to sign your release in base64 encoded format
        signingKeyBase64: ${{ secrets.SIGNING_KEY }} 
        # The key alias
        alias: xiao_wine
        # The password to the keystore
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        # The password for the key
        keyPassword: ${{ secrets.KEY_STORE_PASSWORD }}

 # Example use of `signedReleaseFile` output -- not needed
    - uses: actions/upload-artifact@v2
      with:
        name: Signed app bundle
