name: Automatic Releases

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Grant execute permission for gradlew
      run: each "测试"

